In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [16]:
# このセルの内容は、理解できなくても大丈夫です。
# ただサンプルになるデータを作りたいだけですので、出来たデータをどのような加工するかに注目してください。

#import pandas.util.testing as tm
#tm.N = 3

# ちょっとした関数を作ります。
#def unpivot(frame):
#    N, K = frame.shape
#    data = {'value' : frame.values.ravel('F'),
#            'variable' : np.asarray(frame.columns).repeat(N),
#            'date' : np.tile(np.asarray(frame.index), K)}
#    return DataFrame(data, columns=['date', 'variable', 'value'])

# DataFrameを作ります。
#dframe = unpivot(tm.makeTimeDataFrame())

In [17]:
#@ pandas.util.testingがもうすぐなくなってしまうようなので、サンプルデータを自分で作ります。

d_range = pd.date_range(start='2020/1/1', end='2020/1/8')
names = ['A', 'B', 'C', 'D']
temp = {'value':[], 'variable':[], 'date':[]}

for name in names:
    for day in d_range:
        temp['value'].append(np.random.random())
        temp['variable'].append(name)
        temp['date'].append(day)

dframe = pd.DataFrame(temp)

In [19]:
# 入れ子になったデータができます。
dframe

       value variable       date
0   0.026981        A 2020-01-01
1   0.820583        A 2020-01-02
2   0.524721        A 2020-01-03
3   0.219208        A 2020-01-04
4   0.913482        A 2020-01-05
5   0.983271        A 2020-01-06
6   0.510221        A 2020-01-07
7   0.463569        A 2020-01-08
8   0.888802        B 2020-01-01
9   0.244415        B 2020-01-02
10  0.140642        B 2020-01-03
11  0.960809        B 2020-01-04
12  0.582756        B 2020-01-05
13  0.979276        B 2020-01-06
14  0.173871        B 2020-01-07
15  0.398420        B 2020-01-08
16  0.639825        C 2020-01-01
17  0.976894        C 2020-01-02
18  0.756367        C 2020-01-03
19  0.770621        C 2020-01-04
20  0.927255        C 2020-01-05
21  0.289316        C 2020-01-06
22  0.268967        C 2020-01-07
23  0.993512        C 2020-01-08
24  0.393479        D 2020-01-01
25  0.421634        D 2020-01-02
26  0.270385        D 2020-01-03
27  0.250542        D 2020-01-04
28  0.664838        D 2020-01-05
29  0.802134        D 2020-01-06
30  0.264061        D 2020-01-07
31  0.132165        D 2020-01-08

In [20]:
# 行にdate, 列にvariable、これをvalueで埋めます。
dframe_piv = dframe.pivot('date','variable','value')
dframe_piv

variable           A         B         C         D
date
2020-01-01  0.026981  0.888802  0.639825  0.393479
2020-01-02  0.820583  0.244415  0.976894  0.421634
2020-01-03  0.524721  0.140642  0.756367  0.270385
2020-01-04  0.219208  0.960809  0.770621  0.250542
2020-01-05  0.913482  0.582756  0.927255  0.664838
2020-01-06  0.983271  0.979276  0.289316  0.802134
2020-01-07  0.510221  0.173871  0.268967  0.264061
2020-01-08  0.463569  0.398420  0.993512  0.132165

In [8]:
# どのようなピボットテーブルを作るかは、どのよなデータが欲しいかによります。